name: favorite_places_repeat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  path_provider: ^2.1.2

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
